In [1]:
import numpy as np

In [6]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [7]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
np.random.randn(8).tolist()

[-0.5871592045138736,
 -0.39560507040412074,
 0.6659582192595866,
 -0.38062516628595816,
 -0.973589026000045,
 -1.0715048143824453,
 -0.08139523977058548,
 0.7825645472587244]

In [14]:
print("Tamamlandi")

Tamamlandi


In [19]:
np.random.randint(5, 100)

64

In [20]:
np.random.randint(1, 1000, 10)

array([585, 575, 699, 116, 366, 263, 880, 927, 916, 151])

In [25]:
myRandomArray = np.random.randint(0,500,30)

In [26]:
myRandomArray.reshape(5, 6)

array([[495, 141, 154, 469, 344, 437],
       [324, 169, 483, 292, 434,  11],
       [ 29, 309,   5,  65, 204, 258],
       [271, 152, 267, 494, 343, 333],
       [370, 235, 416, 185, 346, 133]])

In [28]:
myRandomArray.max()

495

In [30]:
myRandomArray.argmax()

0

In [31]:
myRandomArray.argmin()

14